index.html

Fixes #25 Fixed Logo on NavBar

---

index.html

- Added Gitter and Facebook Group links to the navbar

Fixes #26: Added Gitter and Facebook links to Navbar

---

index.html

Linked logo to main website

---

index.html

Reverts fossiiita/opencodecollab#59

Revert "Click on project"

---

_data/students.yml

For issue #68 . Please review.

Corrected records in students.yml

---

index.html
javascripts/issues-loader.js
stylesheets/main.css

This is for #41 as it lists out the current issues of the repo. It is also for #57 because as given in a [note in GitHub Developer](https://developer.github.com/v3/issues/#list-issues-for-a-repository), a pull request is also an issue. So when we query for issues we also get info about pull requests. So it is unnecessary to query separately for PRs again. I distinguished a PR from an issue using icons. Font awesome didn't have icons for github issues and github PRs, so I used the most appropriate ones. Please review.
[Demo](https://vamsisangam.github.io/opencodecollab/)

Implemented issues section

---

index.html
javascripts/issues-loader.js
stylesheets/main.css

For #81 . Added shadows to issue panels. Removed PRs. Page size is fixed to 8. [Demo URL](https://vamsisangam.github.io/opencodecollab/). Please review. Thanks!

Modified issues section

---

_data/projects.yml
index.html
javascripts/repo-stats-loader.js

For #91 . [Demo URL](https://vamsisangam.github.io/opencodecollab/). Uses GitHub API. Needed to make changes in ```projects.yml```. Please review.

Added project stars and forks

---

_data/students.yml

Fix participant not comming

---

_data/students.yml

Added personal website to students.yml

---

_data/scores.yml

Adding empty ```scores.yml```. This is for the rankings as discussed with @gauthamzz  in #64 . After this merge, I will create a new issue asking students to add details of their contributions into this file.

Added scores.yml

---

PULL_REQUEST_TEMPLATE.md
README.md

For #127 . Please review PR template and README. [README demo](https://github.com/VamsiSangam/opencodecollab#opencode-collabrative-website)

Modified README and added PR template

---

index.html

This PR is for the issue #101 
[Live Demo URL](https://vamsisangam.github.io/opencodecollab/)
Added facebook like and share button. I've created an app id. Please review.

Added fb like button

---

_data/scores.yml

Added all my contributions so far in all projects. Please review.

Added contribution details to scores.yml

---

_data/students.yml

add blog link in students.yml

---

index.html
javascripts/index.js
stylesheets/style.css

This PR is for the issue #
[Live Demo URL](your_link_goes_here)

Made Navbar Sticky

---

stylesheets/main.css

This PR is for the issue #123
[Live Demo URL](your_link_goes_here)

Title view Changed

---

_data/scores.yml

This PR is for the issue #128 
[Live Demo URL](your_link_goes_here)

Added scores.

---

_data/projects.yml
index.html
javascripts/issues-loader.js

This PR is for the issue #137 
[Live Demo URL](https://vamsisangam.github.io/opencodecollab/)
Separated each project's issues using accordion. This uses a GitHub API endpoint which does not give us a total count of results, so I removed pagination and replaced it with a "Load more" functionality. Please review.

Implemented separate issues for each project

---

_data/scores.yml

This PR is for the issue #128 
[Live Demo URL](your_link_goes_here)
Updated scores.yml

Updated scores.yml

---

_data/scores.yml
_data/students.yml

This PR is for the issue #108 
[Live Demo URL](https://anupam-dagar.github.io/)
Made website of my username.

Updated students.yml

---

_data/scores.yml
_data/students.yml
stylesheets/main.css

This PR is for the issue #
Updated scores.
[Read once](https://github.com/fossiiita/opencodecollab#contributing)

Updated scores.

---

_data/scores.yml

Updated scores.yml for my [contribution](https://github.com/fossiiita/opencodecollab/pull/150).

Updated score

---

_includes/navbar.html
projects.html

This PR is for the issue #168 
[Live Demo URL](https://vamsisangam.github.io/opencodecollab/)
Created ```projects.html``` for projects and issues. Please review.

Created separate pages

---

_data/scores.yml

Updated scores for respective contributions.

Updated scores

---

_includes/navbar.html
index.html
projects.html

moved trailer and likebox to _includes

---

_includes/navbar.html
index.html
projects.html
scoreboard.html

Deleted the trailer and fb code from projects.html and scorecard.html

---

_data/scores.yml
stylesheets/main.css

This PR is for the issue #128
Added Score

Score Update 

---

_data/scores.yml
projects.html

This PR is for the issue #197 
aswinzz.github.io/opencodecollab/

added chat with us to projects and issues page

---

stylesheets/main.css

Close Chat Box

---

scoreboard.html

This PR is for the issue #212 
[Live Demo URL]https://anupam-dagar.github.io/opencodecollab/ < -- please add your Url over here
[Read once](https://github.com/fossiiita/opencodecollab#contributing)

added chatbox in event scorecard

---

_data/scores.yml
stylesheets/main.css
stylesheets/scoreboard.css

This PR is for the issue #
[Live Demo URL](your_link_goes_here) < -- please add your Url over here
[Read once](https://github.com/fossiiita/opencodecollab#contributing)

 Alignment of contents in scoreboard in mobile view #214

---

_data/students.yml

This PR is for the issue #
[Live Demo URL](your_link_goes_here) < -- please add your Url over here
[Read once](https://github.com/fossiiita/opencodecollab#contributing)

Adding refferal

---

stylesheets/main.css

Fixed Dropdown issue in mobile view

---

_data/students.yml

added referral

---

_data/blog.yml
_data/scores.yml

This PR is for the issue #128 
Updated scores and added blog to blog section.
Decreased score by 20 for codechef programs.

Updated scores and added blog.

---

_data/scores.yml
_includes/navbar.html

This PR is for the issue #132
aswinzz.github.io/opencodecollab/

changed navbar in mobile view

---

_data/students.yml

updated my referral in student.yml

---

_data/blog.yml

i just added my blog to the blogs section

Added my blog ..

---

_data/blog.yml

Added image name

---

_data/blog.yml

changed image extension format

---

_data/scores.yml
_includes/navbar.html

added fork me(github link)

---

_data/scores.yml

Update my scores

---

javascripts/countdown.js

This PR is for the issue #320 
[Live Demo URL](https://vamsisangam.github.io/opencodecollab/)
Fixed countdown.

Fixed countdown

---

_data/scores.yml

Added scores and contributions
